wandb_version: 1

modelName:
  desc: null
  value: nvidia/mit-b0
batchSize:
  desc: null
  value: 6
epochs:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
scheduler:
  desc: null
  value: polynomial
earlyStop:
  desc: null
  value: 10
evalMetric:
  desc: null
  value: mean_iou
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697160927.733029
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 80
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 80
      - 100
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.10
      6: 4.33.2
      8:
      - 3
      - 5
